### ISSUE TITLE
Performance Check

### ISSUE THREAD

**Issue by wl-stepp** [LEB-EPFL/eda-napari#21]

**Comment by elio01epfl** [comment]
Found that the matplotlibs are what make it lag, with around 250ms latency on each frame change

**Comment by elio01epfl** [comment]
When charging the Frame Rate Widget plugin at the begin the matplotlib-based methods in init_data did take around 1500ms to execute, now the qt versions take a ttal of 400ms.
At the change of the frame,the function plot slider position did take around 200-250ms to execute, now the qt counterpart takes less than 100 on average

**Comment by wl-stepp** [comment]
Awesome, good work!
