### ISSUE TITLE
Make widget just 1 figure

### ISSUE THREAD

**Issue by wl-stepp** [LEB-EPFL/eda-napari#6]
In the moment there are two figures in the widget. This also means that both figures have to be redrawn when the layer changes. It might be faster to combine them into one figure (add_subplot(121)) and just redraw that one figure.

https://github.com/LEB-EPFL/eda-napari/blob/master/eda_napari/_widget.py#L57-L62

**Comment by stevenBrownie** [comment]
The plots are now in 1 single figure. The style sheet had to be changed for an optimal viewing.
