### ISSUE TITLE
get_times is called twice

### ISSUE THREAD

**Issue by wl-stepp** [LEB-EPFL/eda-napari#7]
get_times is called twice during the call to plot_frame_data. Even if this function is fast, it still has to open and close the tif file, so it would be best to limit the amount of calls to this function. I think it would be best to store the times in self, and for overview maybe even do this in plot_frame_data.

https://github.com/LEB-EPFL/eda-napari/blob/master/eda_napari/_widget.py#L130
https://github.com/LEB-EPFL/eda-napari/blob/master/eda_napari/_widget.py#L108

**Comment by stevenBrownie** [comment]
I have solved this problem by storing the times and frame_rate in the class as a self variable.
